#ifndef YDWE_VERSION_H_INCLUDED
#define YDWE_VERSION_H_INCLUDED

#define YDWE_VERSION_MAJOR 1
#define YDWE_VERSION_MINOR 31
#define YDWE_VERSION_REVISED 9
#define YDWE_VERSION_BUILD 1000

#endif // YDWE_VERSION_H_INCLUDED
