#ifndef YDWE_VERSION_H_INCLUDED
#define YDWE_VERSION_H_INCLUDED

#define YDWE_VERSION_MAJOR 1
#define YDWE_VERSION_MINOR 31
#define YDWE_VERSION_REVISED 8
#define YDWE_VERSION_BUILD 1850

#endif // YDWE_VERSION_H_INCLUDED
